### mostra tutti i parcheggi
GET http://localhost:8080/parcheggi

### mostra informazione dettagliata di un parcheggio specifico es. parcheggio B tramite la sua id
GET http://localhost:8080/parcheggi/60971350f0d172003a440c8f

### cerca parcheggi per ubicazione geografica
GET http://localhost:8080/parcheggi/search

### crea un parcheggio
POST  http://localhost:8080/parcheggi
Content-Type: application/json

{
  "id": "13971350f0d172003a440c8f",
  "name": "Parking D",
  "fee": 7,
  "maxStop": 1,
  "open": true,
  "coordinates": {
    "nord": 34.0522,
    "est": -118.2437
  },
  "nParkingSpaces": 40,
  "vehicleType": "Motorcycle",
  "nFree": 20,
  "reservations": [
    {
      "timeStart": "2024-05-09T12:00:00Z",
      "timeEnd": "2024-05-09T14:30:00Z"
    }
  ]
}

### aggiorna i parcheggio
PATCH http://localhost:8080/parcheggi/60971350f0d172003a440c8f
Content-Type: application/json

{
    "name": "NUOVO NOME"
}

### elimina un parcheggio
DELETE http://localhost:8080/parcheggi/60971334f0d172003a440c8e
Content-Type: application/json

{
    "reason": "Parcheggio eliminato"
}
