openapi: 3.0.0
info:
  version: 1.0.0
  title: Parcheggio API
  description: API per la gestione delle prenotazioni di parcheggio e il calcolo delle tariffe totali
servers:
  - url: http://localhost:8080/api
paths:
  /{id}/totalFee:
    get:
      summary: Ottieni la somma totale delle tariffe di un parcheggio
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Somma totale delle tariffe ottenuta con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalFee:
                    type: number
                    description: Somma totale delle tariffe
        '404':
          description: Parcheggio non trovato
        '500':
          description: Errore interno del server
  /{id}/updateTotalFee:
    put:
      summary: Aggiorna la somma totale delle tariffe di un parcheggio
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Somma totale delle tariffe aggiornata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parcheggio'
        '404':
          description: Parcheggio non trovato
        '500':
          description: Errore interno del server
components:
  schemas:
    Prenotazione:
      type: object
      properties:
        timeStart:
          type: string
          format: date-time
          description: Ora di inizio della prenotazione
        timeEnd:
          type: string
          format: date-time
          description: Ora di fine della prenotazione
        fee:
          type: number
          description: Tariffa della prenotazione
    Parcheggio:
      type: object
      properties:
        totalFee:
          type: number
          description: Somma totale delle tariffe
