openapi: 3.0.0
info:
  version: 2.0
  title: ParkSpotter API
  description: API for managing parkings
servers:
  - url: http://localhost:8080/api/v2
    description: Localhost
paths:
  /parkings:
    get:
      summary: Get all parkings
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parking'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new parking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parking'
      responses:
        '201':
          description: Parking created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parking'
        '400':
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /parkings/{id}:
    get:
      summary: Get a parking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parking'
        '404':
          description: Parking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      summary: Update a parking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialParking'
      responses:
        '200':
          description: Parking updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parking'
        '400':
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Parking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a parking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Parking deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message indicating the success of the operation
        '404':
          description: Parking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Parking:
      type: object
      properties:
        id:
          type: string
          description: ID of the parking
        name:
          type: string
          description: Name of the parking
        fee:
          type: number
          description: Hourly fee
        maxStop:
          type: number
          description: Maximum stop time in hours
        open:
          type: boolean
          description: Indicate if the parking is available
        coordinates:
          type: object
          properties:
            nord:
              type: number
              description: North coordinate
            est:
              type: number
              description: East coordinate
          description: Geographic coordinates of the parking
        nParkingSpaces:
          type: integer
          description: Total number of parking spaces
        vehicleType:
          type: string
          description: Type of supported vehicle
        nFree:
          type: integer
          description: Number of free parking spaces
        reservations:
          type: array
          items:
            type: object
            properties:
              timeStart:
                type: string
                format: date-time
                description: Reservation start time
              timeEnd:
                type: string
                format: date-time
                description: Reservation end time
          description: Parking reservations
        averageScore:
          type: number
          description: Average score of feedback given by users  
    PartialParking:
      type: object
      properties:
        id:
          type: string
          description: ID of the parking
        name:
          type: string
          description: Name of the parking
        fee:
          type: number
          description: Hourly fee
        maxStop:
          type: number
          description: Maximum stop time in hours
        open:
          type: boolean
          description: Indicate if the parking is available
        coordinates:
          type: object
          properties:
            nord:
              type: number
              description: North coordinate
            est:
              type: number
              description: East coordinate
          description: Geographic coordinates of the parking
        nParkingSpaces:
          type: integer
          description: Total number of parking spaces
        vehicleType:
          type: string
          description: Type of supported vehicle
        nFree:
          type: integer
          description: Number of free parking spaces
        reservations:
          type: array
          items:
            type: object
            properties:
              timeStart:
                type: string
                format: date-time
                description: Reservation start time
              timeEnd:
                type: string
                format: date-time
                description: Reservation end time
          description: Parking reservations
        averageScore:
          type: number
          description: Average score of feedback given by users  
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
