
### File created to review the correct functioning of the endpoints ###

### shows all parking lots
GET http://localhost:8080/api/v1/parkings

### shows detailed information of a specific parking lot e.g. parking B via his id
GET http://localhost:8080/api/v1/parkings/665d73c234bf77f32ff97c09

### creates a parking lot
POST  http://localhost:8080/api/v1/parkings
Content-Type: application/json

{
  "name": "Parking D",
  "fee": 7,
  "maxStop": 1,
  "open": true,
  "coordinates": {
    "nord": 34.0522,
    "est": -118.2437
  },
  "nParkingSpaces": 40,
  "vehicleType": "Motorcycle",
  "nFree": 20,
  "reservations": [],
  "averageScore": 0
}

### upgrade a parking lot
PATCH http://localhost:8080/api/v1/parkings/665d8a3d8a4c0906ded8955d
Content-Type: application/json

{
    "name": "San Severino"
}

### delete a parking lot
DELETE http://localhost:8080/api/v1/parkings/664cd31b4748f814b41f3537
Content-Type: application/json

### Get all feedbacks - just to test
GET http://localhost:8080/api/v1/feedback

### Get one feedback by its id 
GET http://localhost:8080/api/v1/feedback/665d6e08926cddb6d858828c


### Post a new feedback
POST http://localhost:8080/api/v1/feedback
Content-Type: application/json

{
    "user_id": "60c72b2f9b1d4c3b3c1a7b4f",
    "parking_id": "665d8a20a7767a2a220cf99a",
    "score": 5 ,
    "comment": "Great parking spot",
    "date": "2021-06-01T00:00:00.000Z"
}
### Post a new feedback
POST http://localhost:8080/api/v1/feedback
Content-Type: application/json

{
    "user_id": "60c72b2f9b1d4c3b3c1a7b4f",
    "parking_id": "665d8a20a7767a2a220cf99a",
    "score": 3,
    "comment": "Decent parking spot",
    "date": "2021-06-02T00:00:00.000Z"
}


### Delete a feedback by its id
DELETE http://localhost:8080/api/v1/feedback/665d72f447cdab523fefe2ac
Content-Type: application/json



   